ALTER TYPE "PlatformProfitLedgerType" ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_LIABILITY';
ALTER TYPE "PlatformProfitLedgerType" ADD VALUE IF NOT EXISTS 'TRANSACTION_PAYOUT_LIABILITY';
ALTER TYPE "PlatformProfitLedgerType" ADD VALUE IF NOT EXISTS 'TRANSACTION_REFUND_LIABILITY';